
#line 2 "lex.exe.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer exe_create_buffer
#define yy_delete_buffer exe_delete_buffer
#define yy_scan_buffer exe_scan_buffer
#define yy_scan_string exe_scan_string
#define yy_scan_bytes exe_scan_bytes
#define yy_init_buffer exe_init_buffer
#define yy_flush_buffer exe_flush_buffer
#define yy_load_buffer_state exe_load_buffer_state
#define yy_switch_to_buffer exe_switch_to_buffer
#define yypush_buffer_state exepush_buffer_state
#define yypop_buffer_state exepop_buffer_state
#define yyensure_buffer_stack exeensure_buffer_stack
#define yy_flex_debug exe_flex_debug
#define yyin exein
#define yyleng exeleng
#define yylex exelex
#define yylineno exelineno
#define yyout exeout
#define yyrestart exerestart
#define yytext exetext
#define yywrap exewrap
#define yyalloc exealloc
#define yyrealloc exerealloc
#define yyfree exefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define exe_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer exe_create_buffer
#endif

#ifdef yy_delete_buffer
#define exe_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer exe_delete_buffer
#endif

#ifdef yy_scan_buffer
#define exe_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer exe_scan_buffer
#endif

#ifdef yy_scan_string
#define exe_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string exe_scan_string
#endif

#ifdef yy_scan_bytes
#define exe_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes exe_scan_bytes
#endif

#ifdef yy_init_buffer
#define exe_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer exe_init_buffer
#endif

#ifdef yy_flush_buffer
#define exe_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer exe_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define exe_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state exe_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define exe_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer exe_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define exepush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state exepush_buffer_state
#endif

#ifdef yypop_buffer_state
#define exepop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state exepop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define exeensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack exeensure_buffer_stack
#endif

#ifdef yylex
#define exelex_ALREADY_DEFINED
#else
#define yylex exelex
#endif

#ifdef yyrestart
#define exerestart_ALREADY_DEFINED
#else
#define yyrestart exerestart
#endif

#ifdef yylex_init
#define exelex_init_ALREADY_DEFINED
#else
#define yylex_init exelex_init
#endif

#ifdef yylex_init_extra
#define exelex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra exelex_init_extra
#endif

#ifdef yylex_destroy
#define exelex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy exelex_destroy
#endif

#ifdef yyget_debug
#define exeget_debug_ALREADY_DEFINED
#else
#define yyget_debug exeget_debug
#endif

#ifdef yyset_debug
#define exeset_debug_ALREADY_DEFINED
#else
#define yyset_debug exeset_debug
#endif

#ifdef yyget_extra
#define exeget_extra_ALREADY_DEFINED
#else
#define yyget_extra exeget_extra
#endif

#ifdef yyset_extra
#define exeset_extra_ALREADY_DEFINED
#else
#define yyset_extra exeset_extra
#endif

#ifdef yyget_in
#define exeget_in_ALREADY_DEFINED
#else
#define yyget_in exeget_in
#endif

#ifdef yyset_in
#define exeset_in_ALREADY_DEFINED
#else
#define yyset_in exeset_in
#endif

#ifdef yyget_out
#define exeget_out_ALREADY_DEFINED
#else
#define yyget_out exeget_out
#endif

#ifdef yyset_out
#define exeset_out_ALREADY_DEFINED
#else
#define yyset_out exeset_out
#endif

#ifdef yyget_leng
#define exeget_leng_ALREADY_DEFINED
#else
#define yyget_leng exeget_leng
#endif

#ifdef yyget_text
#define exeget_text_ALREADY_DEFINED
#else
#define yyget_text exeget_text
#endif

#ifdef yyget_lineno
#define exeget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno exeget_lineno
#endif

#ifdef yyset_lineno
#define exeset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno exeset_lineno
#endif

#ifdef yywrap
#define exewrap_ALREADY_DEFINED
#else
#define yywrap exewrap
#endif

#ifdef yyalloc
#define exealloc_ALREADY_DEFINED
#else
#define yyalloc exealloc
#endif

#ifdef yyrealloc
#define exerealloc_ALREADY_DEFINED
#else
#define yyrealloc exerealloc
#endif

#ifdef yyfree
#define exefree_ALREADY_DEFINED
#else
#define yyfree exefree
#endif

#ifdef yytext
#define exetext_ALREADY_DEFINED
#else
#define yytext exetext
#endif

#ifdef yyleng
#define exeleng_ALREADY_DEFINED
#else
#define yyleng exeleng
#endif

#ifdef yyin
#define exein_ALREADY_DEFINED
#else
#define yyin exein
#endif

#ifdef yyout
#define exeout_ALREADY_DEFINED
#else
#define yyout exeout
#endif

#ifdef yy_flex_debug
#define exe_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug exe_flex_debug
#endif

#ifdef yylineno
#define exelineno_ALREADY_DEFINED
#else
#define yylineno exelineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[466] =
    {   0,
       82,   82,   85,   83,   78,   79,   70,   80,   81,   83,
       76,   82,   71,   83,   82,   82,   82,   82,   82,   82,
       73,   72,   82,   82,   82,   82,   82,   82,   74,   82,
       82,   82,   82,   82,   82,   70,   68,   69,    0,   76,
        0,    0,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   36,   82,   82,   82,   82,   82,   82,
       82,   82,   47,   82,   82,   82,   82,   48,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       39,   41,   40,   69,   75,   77,   42,   82,   82,   82,
       82,   82,   82,   82,   37,   82,    2,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   82,   62,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   43,   82,    4,   82,   82,
       82,   82,   82,   82,   82,   82,    0,   82,   27,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,    3,   82,    1,   82,   82,   82,
       82,   82,   82,   82,    0,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   56,   82,
       82,   82,   82,    0,   82,   82,   82,   30,   82,   82,
       82,   82,   82,   82,   82,   82,   38,   82,   53,   82,

        0,   82,   82,   82,   82,   82,   82,   82,    0,   82,
       82,   82,    0,   55,   82,   34,   82,   82,   82,   54,
       82,   82,    0,   82,   82,   82,    0,   82,   82,    0,
       82,   82,   82,   82,   82,   82,   82,   82,   59,   82,
        0,   82,   82,   82,   82,   35,   82,   82,    0,    0,
        0,   82,   51,    0,   82,   82,   82,   82,   25,    0,
        0,    0,    0,   82,   82,    0,    0,   82,    0,   32,
       26,   82,   82,   19,   82,   60,   82,   82,    0,   82,
       82,   82,    0,   29,   82,    0,    0,    0,    0,    0,
        5,   61,   82,   82,    0,    0,    0,    0,    0,   82,

        0,    0,    0,   58,    0,   82,   57,   82,   82,   82,
        0,    0,   82,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   82,    0,    0,    0,    0,    0,    0,
       82,    0,    0,    0,    0,    0,   82,   82,    0,   33,
       12,    0,   82,    0,    0,    0,    0,    0,    0,    0,
        0,   18,    0,   52,    0,   49,    0,    0,    0,    0,
       82,    0,    0,    0,    0,    0,   82,   82,    0,    0,
       82,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   50,    0,   31,    0,    7,    0,    0,
        0,   82,    0,    0,    8,   82,    0,    0,    0,    0,

        0,    0,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   64,   82,    0,    0,   24,   44,
       13,    0,    0,    0,   65,   10,   16,   22,   21,    0,
        0,    0,    0,    0,   23,    0,    6,    0,   11,    0,
        0,   28,    0,    0,   45,   46,    0,   66,    0,   63,
        0,    0,    0,   67,    0,    0,    0,    0,    0,    0,
       15,   14,   17,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    2,    1,    1,    4,
        1,    5,    6,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        6,    1,    1,    1,   10,   10,   10,   10,   10,   10,
       10,   11,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        1,    1,    1,    1,   12,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   10,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    4,    4,
        4,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[471] =
    {   0,
        0,    0, 1346, 1347, 1347, 1347,    0, 1347, 1347,   33,
       33,   36,   37, 1338,   43,   68,   88,   50,   53,   47,
       70,   73,   84,  110,  102,  106,  117,  124,  127,   30,
       87,  134,  140,  142,  148,    0, 1347,    0, 1335,   52,
     1336, 1333,  154,  156,  164,  172,  171,  171,  179,  185,
      187,  198,  201,  212,  213,  214,  178,  224,  225,  227,
      234,  239,  241,  236,  252,  257,  268,  265,  279,  273,
      273,  291,  292,  301,  307,  305,  308,  319,  320,  326,
      327,  333,  339,    0, 1332, 1329,  340,  341,  155,  361,
      200,  362,  368,  369,  377,  359,  375,  377,  379,  383,

      382,  395,  403,  406,  407,  410,  421,  423,  427,  434,
      435,  441,  451,  443,  454,  461,  436,  461,  462,  473,
      480,  481,  491,  488,  498,  499,  501,  511,  514,  519,
      525,  528,  463,  530,  534,  542,   58,  543,  550,  556,
      553,  563,  569,  566,  576,  579,  575,  588,  595,  590,
      593,  601,  606,  608,  613,  514,  529,  613,  625,  626,
      627,  636,  639,  640,   88,  649,  650,  652,  603,  653,
      663,  669,  670,  670,  677,  680,  686,  687,  691,  713,
      717,  708,  714,   91,  719,  724,  721,  745,  746,  752,
      753,  761,  767,  761,  743,  770,  767,  768,  779,  780,

      291,  786,  787,  799,  801,  802,  809,  815,  781,  830,
      836,  837,  299,  843,  834,  840,  841,  845,  852,  846,
      858,  873,  256,  880,  863,  870,   46,  887,  894,   85,
      898,  902,  885,  899,  903,  905,  903,  906,  919,  921,
      117,  922,  929,  935,  942,  950,  956,  943,  386,  496,
      145,  964,  965,  210,  971,  964,  965,  967,  977,  143,
      574,  280,  300,  974,  992,  698,   55,  993,  731, 1001,
     1002, 1008, 1001, 1002, 1003, 1008, 1008, 1015,  216, 1035,
     1020, 1042,  417, 1046, 1050,  335,  192,  760, 1039,  616,
     1058, 1062, 1066, 1051,  908,  114,  634,  248,  972, 1059,

     1072,  253,  489, 1065,  701, 1071, 1074, 1076, 1081, 1079,
     1043,  356, 1088,  394,  592,  456,  532,  656,  728,  425,
      810, 1095,  946, 1100,  549,  705,  860,  328,   47,  762,
     1096,  742, 1038,  478, 1091, 1103, 1104, 1104, 1000, 1112,
     1323, 1111, 1122,  817, 1119, 1097, 1124, 1134, 1135, 1023,
      700, 1320, 1137, 1128,  670, 1319,  884,  777, 1139,  844,
     1141,  937, 1140, 1031, 1148, 1145, 1147, 1165, 1150, 1168,
     1162, 1154, 1153, 1174,  959, 1173, 1175, 1178, 1179, 1108,
     1184, 1183, 1185, 1318, 1187, 1176, 1189, 1317, 1192, 1193,
     1196, 1192, 1199, 1205, 1316, 1205, 1210, 1203, 1216, 1221,

     1217, 1223, 1315, 1228, 1229, 1230, 1232, 1236, 1237, 1233,
     1234, 1235, 1243, 1246, 1313, 1241,  628, 1252, 1247, 1312,
     1293, 1250, 1256, 1258, 1158,  934,  890,  737,  668, 1263,
     1265, 1267, 1268, 1270,  621, 1272, 1265, 1274,  551, 1276,
     1277,  424, 1281, 1282,  421,  387, 1280,  357, 1283,  321,
     1288, 1286, 1289,  249, 1304, 1296, 1054, 1290, 1291, 1311,
      165,  138,  103,   92, 1347, 1328, 1330, 1332, 1336,   35
    } ;

static const flex_int16_t yy_def[471] =
    {   0,
      465,    1,  465,  465,  465,  465,  466,  465,  465,  465,
      467,  468,  468,  467,  468,  468,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   24,   24,
       24,   24,   24,   24,   24,  466,  465,  469,  470,  467,
      467,  470,   24,   24,   24,   24,   24,   16,   24,   24,
       24,   24,   24,   24,   24,   24,   16,   24,   24,   24,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   24,
       16,   24,   24,   16,   16,   24,   24,   24,   24,   24,
       24,   24,   24,  469,  465,  470,   24,   24,  468,  468,
      468,  468,  468,  468,  468,   16,   16,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       24,   24,   24,   24,   24,   24,  468,   16,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   15,
       24,   24,   16,   16,   16,   24,  467,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   16,   16,   16,   16,
       16,   16,   16,   16,   16,  468,  468,   24,   24,   24,
       24,   16,   24,   24,  467,   16,   24,   24,  468,   24,
       24,   24,   24,   16,   24,   24,   16,   16,   16,  468,
      468,   16,   16,  467,   16,   24,  468,  468,  468,  468,
      468,  468,  468,   24,   16,   16,   16,   24,   24,   24,

      467,   24,   24,   24,   24,   24,   24,   24,  467,  468,
      468,  468,  467,  468,   16,   16,   16,   16,   16,   16,
       16,  468,  467,  468,   16,   16,  467,  468,  468,  467,
      468,  468,   16,   16,   16,   16,   24,   24,   24,   24,
      467,   24,   24,   24,  468,  468,  468,   24,  467,  467,
      467,  468,  468,  467,  468,   24,   24,   24,   24,  467,
      467,  467,  467,   16,  468,  467,  467,  468,  467,  468,
      468,  468,   24,   24,   16,   16,   24,   24,  467,  468,
       16,  468,  467,  468,  468,  467,  467,  467,  467,  467,
      468,  468,  468,   24,  467,  467,  467,  467,  467,   24,

      467,  467,  467,   24,  467,   16,   16,   16,  468,   24,
      467,  467,   16,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,   16,  467,  467,  467,  467,  467,  467,
       16,  467,  467,  467,  467,  467,   16,   24,  467,   24,
      467,  467,   24,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,   24,  467,  467,  467,  467,  467,  467,
       24,  467,  467,  467,  467,  467,   24,  468,  467,  467,
       24,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,   24,  467,  467,  467,  467,
      467,   24,  467,  467,  467,   24,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,   24,  467,  467,   24,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,   24,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,    0,  465,  465,  465,  465,  465
    } ;

static const flex_int16_t yy_nxt[1385] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   12,   24,   25,   12,   26,   27,   12,   28,   29,
       30,   31,   32,   12,   33,   34,   35,   37,   86,   39,
       38,   40,   42,   42,   41,   41,   43,   41,   41,   42,
       43,   41,   42,   42,   41,   78,   44,   45,   39,   43,
       40,   42,   43,   59,   42,   43,  359,  303,  266,   43,
       55,   46,   43,   47,   42,   43,   41,   57,   43,   41,
       48,   43,   43,   56,   43,   43,   60,   58,  184,   61,
       49,   42,   43,   62,   42,   43,   43,   42,   42,   50,

       43,   43,   51,   43,   43,  209,   43,   43,   63,   42,
       52,   79,   43,   53,   67,   43,  227,  269,   43,   43,
       42,   54,   43,   42,   43,   68,   64,   69,   43,   71,
       65,  326,   43,   43,   70,   66,   73,   43,  327,   43,
       74,   43,  279,   75,   42,   72,   43,   43,   43,   42,
       43,   42,   43,   76,   80,   43,   43,   77,   43,   43,
       43,   42,   43,   41,   43,   43,  137,   43,   43,  295,
       43,   42,   43,   43,   43,   81,   43,  288,   82,   43,
       43,   43,   83,   43,   43,   87,   89,   43,   43,   43,
      103,   43,   43,   43,   88,   92,   90,   43,   42,   43,

       43,   43,   91,   43,   93,   43,   42,   43,   41,   43,
       43,   41,   43,   94,   43,  139,   42,   43,   43,  318,
       95,   43,   42,   96,   98,   99,  100,   97,   43,   43,
      102,  311,   43,   43,   43,  290,  104,   43,   43,   43,
      105,  107,  101,   43,  106,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   42,   42,  109,  108,   43,   42,
      113,   43,   42,   43,   43,   43,  329,   43,  110,   43,
       43,  111,   43,  112,   43,  115,  114,   43,  261,   43,
       43,  334,  116,   43,  262,   43,   42,   43,   43,   43,
       43,   43,  297,  120,  118,   43,   43,   42,   43,   43,

      298,   43,  117,  121,  122,   42,   42,   43,   43,  119,
       43,   43,   43,   43,  241,  125,  123,   43,  124,   43,
      130,  129,  254,  126,  131,   43,  299,   42,   43,   43,
       43,  127,   43,  132,   42,   43,   43,  128,   43,   43,
      134,   42,   43,   43,  133,   43,   43,   43,  358,   43,
      317,   43,   43,   43,  135,   43,   43,   43,   43,   43,
       43,  136,   42,   42,   43,   43,   43,   42,   42,   41,
       41,   43,   41,   41,   42,   42,   41,   41,  342,   41,
       41,   43,  141,   42,  138,   41,  140,   43,   41,   43,
      143,   43,   42,   42,  149,   43,  145,   43,  142,   43,

       42,   43,  286,  144,   43,  147,   43,   43,   43,  146,
       43,  148,  150,   43,   43,   43,  152,  151,   43,   43,
      153,  154,   43,   42,  344,   43,   43,   42,   43,   43,
       42,   42,   43,   43,   43,   43,  156,   43,   43,   43,
      155,   43,   42,   43,   41,   43,   43,  165,  315,   43,
      350,  159,   43,  157,   43,   43,   43,  160,   43,  162,
       43,   43,   42,   43,  158,   43,   43,   43,   43,  161,
       43,   43,  163,  166,   43,   43,   43,   43,   43,   43,
      164,   43,  167,   43,   42,  180,   43,   43,  346,   43,
      364,  168,   43,   43,   43,   42,   43,   43,   43,  169,

       43,   43,   42,  335,   43,   43,   43,   43,  172,  171,
      170,   43,  287,   43,  173,   43,   43,   43,   43,   43,
       42,   43,   41,   43,   43,  201,   43,   43,  175,  174,
       43,   43,   43,   43,   43,   42,   43,   41,   42,   43,
       41,   43,   43,  347,   43,   43,   43,  176,   43,  177,
       43,  178,   43,   43,  179,   42,   43,   42,   43,   43,
      181,   43,   43,  185,  182,   43,   43,  183,   43,   43,
       43,  186,   43,   43,  187,   43,   43,  355,   43,   43,
       42,   43,   43,   43,  189,   43,   43,  193,   43,   43,
      296,  190,   43,  188,   43,   43,  191,   43,   42,  192,

       43,   43,  196,  194,   43,   43,   43,   43,  195,   42,
       43,   41,   43,   43,  213,  197,  345,   43,   43,   43,
       43,   43,   42,  198,   43,   43,   43,   42,   43,   43,
       43,  322,   43,   43,   42,   43,  199,   43,  202,  200,
       42,   43,   43,   43,   43,   43,   43,   43,  206,  328,
       43,   43,   43,  203,  204,   43,   43,  205,   43,  207,
      208,   43,   42,  438,   43,   43,   43,   43,   43,  214,
       43,  210,  212,   43,   42,  211,   42,   43,   43,   43,
       43,  381,  218,   43,  216,   43,   43,  348,   43,   43,
      217,  215,   43,   43,   43,   43,   43,  219,   43,   43,

       43,   43,   43,   43,   42,   43,   42,   42,   43,   43,
      220,   42,  379,   43,  302,  336,  222,  221,   43,   42,
       43,   41,   43,   42,  223,   41,   43,   42,   41,   41,
       43,   43,  230,  228,   42,  356,   43,   42,  226,  225,
       43,   43,  349,   42,  229,   43,  224,  305,   42,   43,
       43,   42,   42,   41,   41,   43,   41,   41,   42,   42,
       41,   41,  362,   41,   41,  237,   42,   42,   42,   41,
      231,  233,   41,   42,   43,   41,  319,   43,   41,   43,
      232,  236,   43,   42,  239,  234,   43,   42,   43,   43,
      360,  235,   43,   43,  238,   43,   43,  249,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,  383,  250,
      240,   43,   43,  243,  242,   43,   42,   43,   43,   43,
      245,   43,   43,   42,   43,   43,   43,   43,  244,   43,
      246,   43,  351,  247,   43,   43,   42,  372,   41,  248,
       43,  251,   42,   42,   41,   41,  255,   41,   41,   42,
       42,   41,   43,   43,   41,  385,   43,   43,   43,  257,
      252,  253,   43,   43,   43,   43,   42,   43,   43,  258,
       43,   43,   43,  256,   43,  264,   43,   43,  357,   42,
       43,   41,   43,   43,  260,   43,   42,  259,   41,   43,
       42,  263,   43,   42,   43,   41,   42,   43,  267,  265,

       42,   43,   41,  382,   42,   41,   41,   43,   42,   41,
       41,   43,  270,   41,   42,   43,  272,   43,  268,  276,
      277,   43,   43,   43,  325,   43,   43,   43,   43,  275,
      273,   43,  271,  274,   43,   43,   43,   43,   43,   43,
       42,  278,   43,   42,   43,   43,   43,   43,   42,   43,
       41,  282,   42,  283,  281,   43,   42,  280,   41,  285,
       43,   41,   42,   43,   41,   42,  387,   41,   43,  353,
       42,   42,   41,   41,  284,  289,   41,   42,   42,   41,
      292,   43,   41,   43,   43,   43,   43,  294,  330,   43,
       43,  400,   43,   43,  291,  293,  300,   43,   42,   42,

       41,   41,   43,  301,   41,   43,   42,   42,   42,   41,
       41,  304,   41,   41,   42,  308,   41,  307,   43,   41,
       43,   43,   43,  369,  309,   43,   43,   43,   43,   42,
       43,   43,   43,   43,   43,   43,  306,   42,  378,   43,
       43,   42,  313,   41,   42,   42,  312,  310,   42,   42,
       41,   43,   42,  314,   41,  389,   42,   41,   41,  341,
       42,  316,  320,  363,   42,  321,   41,  324,   42,   41,
       41,   43,   42,   41,   41,   43,   43,  323,   42,   43,
      461,   43,  331,  337,   43,   43,   43,   42,   43,   41,
       43,  332,  339,   43,  333,  340,   43,   42,   43,   43,

      343,   42,   43,   42,   43,   43,  338,   43,  361,   42,
       43,  352,   43,  374,   42,  354,   43,   42,   43,   43,
      368,  365,   43,  405,   43,   42,   43,   43,   43,   43,
       42,   43,   43,  366,  367,   43,  370,   43,   43,  373,
       42,   42,   43,   42,   43,   42,   42,   43,   43,  375,
      376,   42,  371,   43,   42,  386,   42,   43,  388,   42,
       42,   43,  380,   43,   42,  377,   43,  392,  390,  384,
      391,   42,   43,   41,   42,  394,  393,  397,   43,   42,
       42,   42,   43,  398,   42,   42,  395,  396,  399,   42,
       42,   42,   43,   42,  403,   42,   43,  401,   42,   42,

      402,   43,   42,  404,  406,   42,  413,  407,   43,   42,
      410,   42,   43,  408,  409,  411,   42,  416,  414,  412,
      418,   43,   42,   42,  415,   43,  420,   42,  417,   42,
       43,  424,  421,  419,   42,   42,   42,  423,   42,   42,
       42,   42,   42,   42,  426,  427,  422,  430,  431,   42,
      433,  425,   42,  432,  428,  429,   42,   43,   42,  435,
      434,   43,   42,   43,   42,  437,   43,   43,  439,   42,
      436,   42,   43,   42,   42,  440,   42,  443,   42,  444,
       42,   43,   42,   42,  441,   43,   42,   42,   42,   42,
       43,  445,   42,  442,   42,   42,   42,   42,  447,   42,

      446,  448,   42,  449,  450,  451,  452,  453,  456,  457,
       42,  460,  458,  455,  463,  454,  462,   42,   42,   42,
      459,   42,   42,   42,   42,   42,   42,  464,   36,   42,
       36,   36,   41,   41,   43,   43,   84,  465,   84,   84,
       85,  465,   42,   85,   42,  465,    3,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465
    } ;

static const flex_int16_t yy_chk[1385] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   10,  470,   11,
       10,   11,   12,   13,   12,   13,   30,   12,   13,   15,
       30,   15,  227,  329,   15,   30,   15,   15,   40,   20,
       40,  267,   18,   20,  137,   19,  329,  267,  227,   20,
       18,   15,   18,   15,   16,   19,   16,   19,   20,   16,
       16,   18,   21,   18,   19,   22,   21,   19,  137,   22,
       16,  230,   21,   22,  165,   22,   23,  184,  464,   16,

       17,   21,   17,   31,   22,  165,   23,   31,   23,  463,
       17,   31,   31,   17,   25,   23,  184,  230,   26,   17,
      296,   17,   24,  241,   25,   25,   24,   25,   26,   27,
       24,  296,   24,   25,   26,   24,   28,   26,  296,   27,
       28,   24,  241,   29,  462,   27,   28,   29,   27,  260,
       32,  251,   29,   29,   32,   28,   33,   29,   34,   32,
       33,   89,   34,   89,   35,   33,   89,   34,   35,  260,
       43,  461,   44,   35,   43,   33,   44,  251,   34,   43,
       45,   44,   35,   48,   45,   44,   46,   47,   46,   45,
       57,   47,   46,   48,   45,   49,   47,   46,  287,   49,

       57,   50,   48,   51,   49,   50,   91,   51,   91,   57,
       50,   91,   51,   50,   52,   91,  254,   53,   52,  287,
       51,   53,  279,   52,   53,   53,   53,   52,   54,   55,
       56,  279,   54,   55,   56,  254,   58,   54,   55,   56,
       58,   59,   55,   60,   58,   59,   61,   60,   64,   58,
       59,   62,   60,   63,  298,  454,   61,   60,   64,  302,
       64,   62,  223,   63,   65,   61,  298,   64,   62,   66,
       62,   63,   63,   63,   65,   66,   65,   68,  223,   66,
       67,  302,   67,   65,  223,   71,  262,   68,   66,   70,
       67,   69,  262,   70,   69,   71,   68,  201,   70,   67,

      262,   69,   67,   71,   71,  213,  263,   72,   73,   69,
       69,   72,   73,   74,  201,   74,   72,   73,   73,   75,
       77,   76,  213,   74,   77,   76,  263,  450,   77,   75,
       76,   74,   74,   77,  328,   78,   79,   75,   75,   78,
       79,  286,   80,   81,   78,   79,   80,   81,  328,   82,
      286,   80,   81,   82,   80,   83,   87,   88,   82,   83,
       87,   88,  312,  448,   83,   87,   88,   90,   92,   90,
       92,   96,   90,   92,   93,   94,   93,   94,  312,   93,
       94,   96,   93,   95,   90,   95,   92,   97,   95,   98,
       96,   99,  249,  446,  101,  100,   99,   97,   94,   98,

      314,   99,  249,   98,  101,  100,   97,  102,   98,   99,
       99,  100,  101,  101,  100,  103,  103,  102,  104,  105,
      104,  105,  106,  283,  314,  103,  102,  445,  104,  105,
      442,  320,  106,  107,  103,  108,  107,  104,  105,  109,
      106,  106,  117,  107,  117,  108,  110,  117,  283,  109,
      320,  111,  107,  109,  108,  111,  110,  112,  109,  114,
      111,  112,  316,  114,  110,  110,  112,  113,  114,  113,
      115,  113,  115,  118,  115,  133,  113,  116,  119,  115,
      116,  116,  119,  118,  334,  133,  116,  119,  316,  120,
      334,  120,  118,  120,  133,  303,  121,  122,  120,  121,

      121,  122,  250,  303,  124,  121,  122,  123,  124,  123,
      122,  123,  250,  124,  125,  126,  123,  127,  125,  126,
      156,  127,  156,  125,  126,  156,  127,  128,  129,  127,
      129,  128,  130,  130,  129,  157,  128,  157,  317,  129,
      157,  131,  134,  317,  132,  131,  135,  130,  132,  130,
      131,  131,  134,  132,  132,  325,  135,  439,  136,  138,
      134,  134,  136,  138,  135,  135,  139,  136,  138,  141,
      139,  140,  140,  141,  141,  139,  140,  325,  141,  142,
      261,  140,  144,  142,  143,  143,  144,  147,  142,  143,
      261,  144,  145,  142,  143,  146,  145,  147,  315,  146,

      148,  145,  150,  148,  146,  151,  147,  149,  149,  169,
      148,  169,  150,  152,  169,  151,  315,  149,  153,  148,
      154,  150,  290,  152,  151,  155,  149,  435,  153,  158,
      154,  290,  152,  158,  417,  155,  153,  153,  158,  154,
      297,  159,  160,  161,  155,  159,  160,  161,  162,  297,
      159,  160,  161,  159,  160,  163,  164,  161,  162,  163,
      164,  166,  318,  417,  163,  164,  167,  162,  168,  170,
      167,  166,  168,  170,  429,  167,  355,  168,  170,  171,
      166,  355,  174,  171,  172,  172,  173,  318,  171,  172,
      173,  171,  174,  175,  172,  173,  176,  175,  177,  178,

      176,  174,  175,  179,  266,  176,  351,  305,  177,  178,
      176,  326,  351,  179,  266,  305,  178,  177,  178,  180,
      182,  180,  179,  181,  180,  181,  183,  187,  181,  187,
      182,  185,  187,  185,  319,  326,  183,  269,  183,  182,
      186,  185,  319,  428,  186,  183,  181,  269,  332,  186,
      185,  188,  189,  188,  189,  195,  188,  189,  190,  191,
      190,  191,  332,  190,  191,  195,  288,  192,  330,  192,
      189,  191,  192,  193,  195,  193,  288,  194,  193,  197,
      190,  194,  196,  358,  198,  192,  194,  209,  198,  197,
      330,  193,  196,  198,  196,  199,  200,  209,  197,  199,

      200,  196,  202,  203,  199,  200,  202,  203,  358,  209,
      200,  202,  203,  203,  202,  204,  321,  205,  206,  204,
      205,  205,  206,  344,  204,  207,  205,  206,  204,  207,
      206,  208,  321,  207,  207,  208,  210,  344,  210,  208,
      208,  210,  211,  212,  211,  212,  215,  211,  212,  214,
      360,  214,  216,  217,  214,  360,  215,  218,  220,  218,
      211,  212,  216,  217,  219,  215,  327,  218,  220,  219,
      221,  216,  217,  217,  219,  225,  218,  220,  327,  222,
      221,  222,  226,  219,  222,  225,  224,  221,  224,  221,
      357,  224,  226,  228,  225,  228,  427,  233,  228,  226,

      229,  226,  229,  357,  231,  229,  231,  233,  232,  231,
      232,  234,  231,  232,  295,  235,  233,  236,  229,  237,
      238,  234,  238,  237,  295,  235,  238,  236,  237,  236,
      234,  238,  232,  235,  235,  239,  236,  240,  242,  239,
      426,  240,  242,  362,  239,  243,  240,  242,  245,  243,
      245,  244,  323,  245,  243,  244,  246,  242,  246,  248,
      244,  246,  247,  248,  247,  375,  362,  247,  248,  323,
      252,  253,  252,  253,  247,  252,  253,  255,  299,  255,
      256,  257,  255,  258,  256,  257,  264,  258,  299,  256,
      257,  375,  258,  259,  255,  257,  264,  259,  265,  268,

      265,  268,  259,  265,  268,  264,  339,  270,  271,  270,
      271,  268,  270,  271,  272,  275,  272,  273,  274,  272,
      276,  273,  274,  339,  277,  275,  273,  274,  277,  350,
      276,  278,  281,  277,  275,  278,  272,  364,  350,  276,
      278,  280,  281,  280,  333,  289,  280,  278,  282,  311,
      282,  281,  284,  282,  284,  364,  285,  284,  285,  311,
      457,  285,  289,  333,  291,  289,  291,  294,  292,  291,
      292,  294,  293,  292,  293,  300,  294,  293,  301,  300,
      457,  304,  300,  306,  300,  304,  307,  309,  308,  309,
      304,  301,  309,  306,  301,  310,  307,  335,  308,  310,

      313,  322,  306,  346,  310,  307,  308,  308,  331,  336,
      313,  322,  324,  346,  380,  324,  337,  342,  331,  313,
      338,  335,  324,  380,  338,  345,  337,  331,  340,  338,
      347,  324,  340,  336,  337,  337,  342,  340,  343,  345,
      348,  349,  343,  353,  354,  359,  363,  343,  354,  347,
      348,  366,  343,  354,  365,  361,  369,  361,  363,  373,
      372,  361,  353,  367,  425,  349,  361,  367,  365,  359,
      366,  368,  367,  368,  370,  369,  368,  372,  371,  376,
      374,  377,  371,  373,  378,  379,  370,  371,  374,  382,
      381,  383,  386,  385,  378,  387,  386,  376,  389,  390,

      377,  386,  391,  379,  381,  393,  389,  381,  392,  398,
      385,  394,  392,  382,  383,  385,  397,  392,  390,  387,
      394,  396,  399,  401,  391,  396,  397,  400,  393,  402,
      396,  401,  398,  396,  404,  405,  406,  400,  407,  410,
      411,  412,  408,  409,  404,  405,  399,  408,  409,  413,
      411,  402,  414,  410,  406,  407,  422,  416,  418,  413,
      412,  416,  423,  419,  424,  416,  416,  419,  418,  430,
      414,  431,  419,  432,  433,  422,  434,  430,  436,  431,
      438,  437,  440,  441,  423,  437,  447,  443,  444,  449,
      437,  432,  452,  424,  451,  453,  458,  459,  434,  421,

      433,  436,  456,  438,  440,  441,  443,  444,  451,  452,
      455,  456,  453,  449,  459,  447,  458,  460,  420,  415,
      455,  403,  395,  388,  384,  356,  352,  460,  466,  341,
      466,  466,  467,  467,  468,  468,  469,   86,  469,  469,
       85,   42,   41,   39,   14,    3,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "exeparser.l"
/***************************************************
 * easyMAC Executive parser 1.0                    *
 * Lexical scanner      				           *
 *                                                 *
 * Jorge Correa & Placid Ferreira                  *
 * 2016                                            *
 *                                                 *
 ***************************************************/
/*
 * This instance of the program contais the executive's parser lexical definitions (token 
 * identifications and return values). 
 *
 * execlval  : is a union declared in bison to store different data types passed from the
 * 			   scanner to the parser. 
 * exectex   : exetext is an array of characters, which acts as a buffer for the input currently being parsed.
 * execlex   : returns the value of the token currently being parsed as an integer. 
 * execlineno: this gives the line number for input currently being parsed
 */
#line 22 "exeparser.l"
	
#include "exe.tab.hpp"
#include "exeparser.h"   

#ifdef _WIN32
    #define YY_NO_UNISTD_H 1  // Prevents <unistd.h> from being included
	#include <io.h>           // Windows equivalent for isatty
#endif

static void comment(void);

#line 1212 "lex.exe.c"
/* Add this to get line numbers...(only in windows) */
#line 1214 "lex.exe.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "exeparser.l"

#line 1433 "lex.exe.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 466 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1347 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "exeparser.l"
{return HELP; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "exeparser.l"
{return CLS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "exeparser.l"
{return EXIT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "exeparser.l"
{return SET;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "exeparser.l"
{return PROGRAM;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "exeparser.l"
{return CONFIGURATION;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "exeparser.l"
{return ACTIONS_LOG;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "exeparser.l"
{return HISTORY_LOG;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "exeparser.l"
{return MOTION_MODE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "exeparser.l"
{return MOTION_PLANE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "exeparser.l"
{return DISTANCE_MODE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "exeparser.l"
{return FEED_MODE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "exeparser.l"
{return LENGTH_UNITS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "exeparser.l"
{return TOOL_RADIUS_COMP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "exeparser.l"
{return TOOL_LENGTH_COMP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "exeparser.l"
{return RETRACT_MODE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "exeparser.l"
{return COORDINATE_SYSTEM;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "exeparser.l"
{return PATH_MODE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "exeparser.l"
{return COOLANT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "exeparser.l"
{return MAX_FEED_OVERRIDE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "exeparser.l"
{return STEPS_PER_MM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "exeparser.l"
{return STEPS_PER_IN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "exeparser.l"
{return ARC_TOLERANCE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "exeparser.l"
{return INTERPOLATOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "exeparser.l"
{return STATUS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "exeparser.l"
{return COMPORT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "exeparser.l"
{return BAUD;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "exeparser.l"
{return MAX_FRQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "exeparser.l"
{return LOGGING;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "exeparser.l"
{return BURST;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "exeparser.l"
{return VIRTUALMAC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "exeparser.l"
{return CLOUDNC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "exeparser.l"
{return EXECUTIVE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "exeparser.l"
{/* could define a generic type STRING [a-zA-Z]+ with the disadvange 
										 of not been able to identify unexpected commands*/
										 exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;} 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "exeparser.l"
{exelval.sval = &exetext[0]; return STRING;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 106 "exeparser.l"
{return GET; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 107 "exeparser.l"
{return MACHINE_VECTOR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 108 "exeparser.l"
{return BLOCK_VECTOR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 109 "exeparser.l"
{return MODAL_VECTOR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 110 "exeparser.l"
{return ATOMIC_ACTIONS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 111 "exeparser.l"
{return ACTIONS_HISTORY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "exeparser.l"
{comment(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "exeparser.l"
{ /* consume //-comment */ }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "exeparser.l"
{ /* consume //-comment */ }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "exeparser.l"
{exelval.id   = yytext[0]; return T_H;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "exeparser.l"
{exelval.id   = yytext[0]; return T_h;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "exeparser.l"
{exelval.id   = yytext[0]; return T_g;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "exeparser.l"
{exelval.id   = yytext[0]; return T_s;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 121 "exeparser.l"
{exelval.fnum = atof(exetext); return FNUMBER;} 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 122 "exeparser.l"
{exelval.num  = atoi(exetext); return NUMBER;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 "exeparser.l"
{// we have to copy because we can't rely on exetext not changing underneath us:
										 char *res = new char[strlen(exetext) + 1];
										 strcpy(res, exetext);
										 exelval.sval = res;
										 return FILENAME;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "exeparser.l"
; 
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 129 "exeparser.l"
{return '\n';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "exeparser.l"
{return '*';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "exeparser.l"
{return exetext[0];}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "exeparser.l"
{ECHO; exeerror(" unexpected command");}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "exeparser.l"
{ECHO; exeerror(" unexpected character");}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 134 "exeparser.l"
ECHO;
	YY_BREAK
#line 1927 "lex.exe.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 466 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 466 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 465);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 134 "exeparser.l"


int exewrap (void) {return 1;}

static void comment(void)
{
	int c;

	while ((c = yyinput()) != 0)
		if (c == '*')
		{
			while ((c = yyinput()) == '*')
				;

			if (c == '/')
				return;

			if (c == 0)
				break;
		}
	exeerror("unterminated comment");
}

/* 
 *yy_scan_string and yy_delete_buffer is defined as static in exe.lex.cc. 
 * therefore they cannot be defined extern in exeparser.h
 */

void exescan_string(char *str)
{
    exe_scan_string(str);    
}

void exedelete_buffer(void)
{
    exe_delete_buffer(YY_CURRENT_BUFFER);
}

